/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Hicran Yoeruek
 */
public class LieferantBearbeiten extends javax.swing.JInternalFrame {

    /**
     * Creates new form LieferantBearbeiten
     */
    public LieferantBearbeiten() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LieferantBearbeiten = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jbzurueck_LieferantBearbeiten = new javax.swing.JButton();
        jSeparator18 = new javax.swing.JSeparator();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        LieferantBearbeiten.setPreferredSize(new java.awt.Dimension(1200, 800));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Lieferant Bearbeiten");

        jbzurueck_LieferantBearbeiten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/zurück.png"))); // NOI18N
        jbzurueck_LieferantBearbeiten.setText("Zurück");
        jbzurueck_LieferantBearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbzurueck_LieferantBearbeitenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LieferantBearbeitenLayout = new javax.swing.GroupLayout(LieferantBearbeiten);
        LieferantBearbeiten.setLayout(LieferantBearbeitenLayout);
        LieferantBearbeitenLayout.setHorizontalGroup(
            LieferantBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LieferantBearbeitenLayout.createSequentialGroup()
                .addGroup(LieferantBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LieferantBearbeitenLayout.createSequentialGroup()
                        .addGroup(LieferantBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LieferantBearbeitenLayout.createSequentialGroup()
                                .addGap(356, 356, 356)
                                .addComponent(jbzurueck_LieferantBearbeiten))
                            .addGroup(LieferantBearbeitenLayout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(jLabel12)))
                        .addGap(0, 502, Short.MAX_VALUE))
                    .addComponent(jSeparator18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        LieferantBearbeitenLayout.setVerticalGroup(
            LieferantBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LieferantBearbeitenLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addGap(15, 15, 15)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jbzurueck_LieferantBearbeiten)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1041, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LieferantBearbeiten, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(LieferantBearbeiten, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbzurueck_LieferantBearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbzurueck_LieferantBearbeitenActionPerformed
        // Hicran Yoeruek
        // Schließt das Fenster nach Betätigung des Abbrech Buttons komplett.
        this.setVisible(false);
    }//GEN-LAST:event_jbzurueck_LieferantBearbeitenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LieferantBearbeiten;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JButton jbzurueck_LieferantBearbeiten;
    // End of variables declaration//GEN-END:variables
}
